<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-105EU33" failures="1" tests="3" name="qa.runners.tc2Runner" time="43.366" errors="0" timestamp="2025-05-19T11:47:20 MST" skipped="0">
  <testcase classname="qa.runners.tc2Runner" name="runScenario" time="16.046">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at qa.stepDefinitions.tc2StepDefinition.validate_first_entry_name_is(tc2StepDefinition.java:62)
at âœ½.validate first entry name is "A Wave From It All"(file:///C:/Users/mengj/Documents/QA_Projects/OneOak/src/test/resources/featureFiles/TestCase2.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="qa.runners.tc2Runner" name="runScenario" time="13.744"/>
  <testcase classname="qa.runners.tc2Runner" name="runScenario" time="13.576"/>
</testsuite> <!-- qa.runners.tc2Runner -->
